# Generated by Django 6.0.3 on 2026-03-21 01:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('capacidad_economica', models.PositiveIntegerField(default=120)),
                ('capacidad_ejecutiva', models.PositiveIntegerField(default=30)),
                ('capacidad_primera_clase', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('puesto', models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('auxiliar', 'Auxiliar de vuelo'), ('tecnico', 'Técnico de tierra'), ('mostrador', 'Agente de mostrador')], max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('licencia', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clase', models.CharField(choices=[('economica', 'Económica'), ('ejecutiva', 'Ejecutiva'), ('primera_clase', 'Primera Clase')], max_length=20)),
                ('tipo_viaje', models.CharField(choices=[('ida', 'Solo ida'), ('redondo', 'Vuelo redondo'), ('grupal', 'Vuelo grupal')], default='ida', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('check_in', 'Check-in realizado'), ('abordado', 'Abordado')], default='pendiente', max_length=20)),
                ('tua_opcion', models.CharField(choices=[('ahora', 'Pagar TUA ahora'), ('despues', 'Pagar TUA después (check-in)')], default='ahora', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipaje_extra', models.PositiveIntegerField(default=0, help_text='Número de maletas extra')),
                ('asientos_seleccionados', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tua_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extras_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('menor', 'Menor de edad'), ('tercera_edad', 'Tercera edad'), ('discapacidad', 'Persona con discapacidad')], default='adulto', max_length=20)),
                ('numero_pasaporte', models.CharField(blank=True, max_length=20)),
                ('nacionalidad', models.CharField(default='Mexicana', max_length=60)),
                ('asiento', models.CharField(blank=True, max_length=5)),
                ('necesidades_especiales', models.TextField(blank=True)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='AEROLINEA.reservacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('paypal', 'PayPal'), ('mostrador', 'En mostrador')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('ultimos_4', models.CharField(blank=True, max_length=4)),
                ('nombre_titular', models.CharField(blank=True, max_length=100)),
                ('reservacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='AEROLINEA.reservacion')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=10, unique=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('precio_economica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_ejecutiva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_primera_clase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tua', models.DecimalField(decimal_places=2, default=310.0, max_digits=8)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('embarque', 'En embarque'), ('en_vuelo', 'En vuelo'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado')], default='programado', max_length=20)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='AEROLINEA.avion')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_llegada', to='AEROLINEA.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_salida', to='AEROLINEA.aeropuerto')),
                ('tripulacion', models.ManyToManyField(blank=True, related_name='vuelos_asignados', to='AEROLINEA.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='reservacion',
            name='vuelo_ida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='AEROLINEA.vuelo'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='vuelo_regreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones_regreso', to='AEROLINEA.vuelo'),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_boleto', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asiento', models.CharField(max_length=5)),
                ('clase', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('check_in_realizado', models.BooleanField(default=False)),
                ('abordado', models.BooleanField(default=False)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='AEROLINEA.pasajero')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='AEROLINEA.reservacion')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='AEROLINEA.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('empleado', 'Empleado')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=150)),
                ('numero_pasajeros', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(9)])),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('estado', models.CharField(choices=[('cotizacion', 'En cotización'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='cotizacion', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('reservacion_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupal', to='AEROLINEA.reservacion')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
    ]
