# Generated by Django 6.0.3 on 2026-03-30 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEROLINEA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='aeropuertos/'),
        ),
        migrations.CreateModel(
            name='ImagenAeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='aeropuertos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AEROLINEA.aeropuerto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
