# Generated by Django 6.0.3 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEROLINEA', '0002_aeropuerto_imagen_imagenaeropuerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='checkin_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
