# Generated by Django 6.0.3 on 2026-04-05 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEROLINEA', '0006_solicitudgrupal_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciongrupal',
            name='precio_cotizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservaciongrupal',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservacion_grupal', to='AEROLINEA.solicitudgrupal'),
        ),
    ]
