# Generated by Django 6.0.3 on 2026-04-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEROLINEA', '0007_reservaciongrupal_precio_cotizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1),
        ),
    ]
