# Generated by Django 6.0.3 on 2026-04-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEROLINEA', '0008_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
